/**
 * Playwright global setup: writes a .env file so that Astro/Vite
 * can resolve import.meta.env vars (API_BASE_URL, etc.) during SSR.
 *
 * Vite only exposes PUBLIC_* vars from process.env to import.meta.env.
 * Non-public vars must come from .env files. This setup ensures the
 * mock API server URL is available to the Astro dev server.
 *
 * The .env file is gitignored so this won't affect the repo.
 */
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ENV_PATH = resolve(import.meta.dirname, '..', '.env');
const BACKUP_PATH = ENV_PATH + '.e2e-backup';

const ENV_CONTENT = `# Auto-generated by Playwright E2E global setup — do not commit
API_BASE_URL=http://localhost:4322
PUBLIC_API_BASE_URL=http://localhost:4322
DEFAULT_MERCHANT=bar-sumac
CUSTOM_DOMAINS={}
PUBLIC_POSTHOG_KEY=
PUBLIC_POSTHOG_HOST=
PUBLIC_ENVIRONMENT=test
AUTH_COOKIE_DOMAIN=.localhost
AUTH_COOKIE_SECURE=false
`;

export default function globalSetup() {
  // Back up existing .env if present
  if (existsSync(ENV_PATH)) {
    const existing = readFileSync(ENV_PATH, 'utf-8');
    writeFileSync(BACKUP_PATH, existing);
  }

  writeFileSync(ENV_PATH, ENV_CONTENT);
}
